services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 5
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:4000
      POSTHOG_PROJECT_ID: 67446

volumes:
  pg_data:
